config/routes.rb
Meugwcel::Application.routes.draw do

	root :to => 'parametros#index'

	resources :operadoras
	#resources :parametros

	controller :parametros do
		post '/parametros',		:action =>:create
		get  '/parametros',		:action =>:index, :as => :parametros
		#get  '/parametros2/',	:action =>:index2, :as => :parametros2

		get '/string',				:action =>:string
		get	'/parametros/consulta', :action =>:consulta
		#get '/parametros/consulta2',:action =>:consulta2 
	end

	resources :filiais
	resources :tipos
	
end

app/controllers/filiais_controller.rb
class FiliaisController < ApplicationController
  # GET /filiais
  # GET /filiais.json
  def index
    @filiais = Filial.order(:nome)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @filiais }
    end
  end

  # GET /filiais/1
  # GET /filiais/1.json
  def show
    @filial = Filial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @filial }
    end
  end

  # GET /filiais/new
  # GET /filiais/new.json
  def new
    @filial = Filial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @filial }
    end
  end

  # GET /filiais/1/edit
  def edit
    @filial = Filial.find(params[:id])
  end

  # POST /filiais
  # POST /filiais.json
  def create
    @filial = Filial.new(params[:filial])

    respond_to do |format|
      if @filial.save
        format.html { redirect_to @filial, notice: 'Filial was successfully created.' }
        format.json { render json: @filial, status: :created, location: @filial }
      else
        format.html { render action: "new" }
        format.json { render json: @filial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /filiais/1
  # PUT /filiais/1.json
  def update
    @filial = Filial.find(params[:id])

    respond_to do |format|
      if @filial.update_attributes(params[:filial])
        format.html { redirect_to @filial, notice: 'Filial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @filial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filiais/1
  # DELETE /filiais/1.json
  def destroy
    @filial = Filial.find(params[:id])
    @filial.destroy

    respond_to do |format|
      format.html { redirect_to filiais_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/filiais_helper.rb
module FiliaisHelper
end

app/views/filiais/_form.html.erb
<%= form_for(@filial,:html => {:class =>"well form-vertical"}) do |f| %>

  <% if @filial.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@filial.errors.count, t(:error)) %>:</h2>
      <ul>
      <% @filial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operadora_id %>
    <%= f.collection_select :operadora_id,
				Operadora.order(:nome),
				:id,
				:nome,
				{:prompt =>true}
    %>
  </div>
  <div class="field">
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit t(:submit),:class =>"btn btn-success" %> | <%= link_to t(:back), filiais_path, :class =>"btn btn" %>
  </div>
  
<% end %>

app/views/filiais/edit.html.erb
<h1>Editing filial</h1>

<%= render 'form' %>

<%= link_to 'Show', @filial %> |
<%= link_to 'Back', filiais_path %>

app/views/filiais/index.html.erb
<h1><%=t(:list_affiliates)%></h1>

<table class="table">
  <tr>
    <th>Código</th>
    <th>Filial</th>
    <th>Operadora</th>

    <th></th>  
    <th>Ações</th>
    <th></th>
  </tr>

<% @filiais.each do |filial| %>
  <tr>
    <td><%= filial.codigo %></td>
    <td><%= filial.nome %></td>

    
    <td><%= filial.operadora.nome %></td>
    

    <td><%= link_to t(:show), filial,:class=>"btn btn-info" %></td>
    <td><%= link_to t(:edit), edit_filial_path(filial),:class=>"btn btn-warning" %></td>
    <td><%= link_to t(:destroy), filial, confirm: 'Are you sure?', method: :delete,:class=>"btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:new), new_filial_path, :class=>"btn btn-primary" %>

app/views/filiais/new.html.erb
<h1><%= t(:new_affiliate)%></h1>

<%= render 'form' %>

app/views/filiais/show.html.erb
<h1><%= t(:details)%></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Operadora:</b>
  <%= @filial.operadora.nome %>
</p>

<p>
  <b>Codigo:</b>
  <%= @filial.codigo %>
</p>

<p>
  <b>Nome:</b>
  <%= @filial.nome %>
</p>


<%= link_to t(:edit), edit_filial_path(@filial),:class =>"btn btn-warning" %> | <%= link_to t(:back), filiais_path,:class=>"btn btn" %>