config/routes.rb
Meugwcel::Application.routes.draw do

	root :to => 'parametros#index'

	resources :operadoras
	#resources :parametros

	controller :parametros do
		post '/parametros',		:action =>:create
		get  '/parametros',		:action =>:index, :as => :parametros
		#get  '/parametros2/',	:action =>:index2, :as => :parametros2

		get '/string',				:action =>:string
		get	'/parametros/consulta', :action =>:consulta
		#get '/parametros/consulta2',:action =>:consulta2 
	end

	resources :filiais
	resources :tipos
	
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
	attr_accessible :codigo, :nome

	has_many :operadoras

	validates_presence_of :codigo,	:message =>"- Dever ser preenchido"
	validates_presence_of :nome,	:message =>"- Dever ser preenchido"

end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipos }
    end
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipo }
    end
  end

  # GET /tipos/new
  # GET /tipos/new.json
  def new
    @tipo = Tipo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipo }
    end
  end

  # GET /tipos/1/edit
  def edit
    @tipo = Tipo.find(params[:id])
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(params[:tipo])

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render json: @tipo, status: :created, location: @tipo }
      else
        format.html { render action: "new" }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipos/1
  # PUT /tipos/1.json
  def update
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      if @tipo.update_attributes(params[:tipo])
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo = Tipo.find(params[:id])
    @tipo.destroy

    respond_to do |format|
      format.html { redirect_to tipos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_for(@tipo,:html => {:class =>"well form-vertical"}) do |f| %>

  <% if @tipo.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@tipo.errors.count, t(:error)) %>:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit t(:submit),:class =>"btn btn-success" %> | <%= link_to t(:back), tipos_path, :class =>"btn btn" %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<h1><%=t(:list_types)%></h1>

<table class="table">
  <tr>
    <th>Codigo</th>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipos.each do |tipo| %>
  <tr>
    <td><%= tipo.codigo %></td>
    <td><%= tipo.nome %></td>
    <td><%= link_to t(:show), tipo,:class=>"btn btn-info" %></td>
    <td><%= link_to t(:edit), edit_tipo_path(tipo),:class=>"btn btn-warning" %></td>
    <td><%= link_to t(:destroy), tipo, confirm: 'Are you sure?', method: :delete,:class=>"btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:new), new_tipo_path,:class=>"btn btn-primary" %>

app/views/tipos/new.html.erb
<h1><%= t(:new_type)%></h1>

<%= render 'form' %>

app/views/tipos/show.html.erb
<h1><%= t(:details)%></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @tipo.codigo %>
</p>

<p>
  <b>Nome:</b>
  <%= @tipo.nome %>
</p>


<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>