config/routes.rb
Meugwcel::Application.routes.draw do

	root :to => 'parametros#index'

	resources :operadoras
	#resources :parametros

	controller :parametros do
		post '/parametros',		:action =>:create
		get  '/parametros',		:action =>:index, :as => :parametros
		#get  '/parametros2/',	:action =>:index2, :as => :parametros2

		get '/string',				:action =>:string
		get	'/parametros/consulta', :action =>:consulta
		#get '/parametros/consulta2',:action =>:consulta2 
	end

	resources :filiais
	resources :tipos
	
end

app/models/operadora.rb
class Operadora < ActiveRecord::Base
	attr_accessible :tipo_id, :codigo, :nome
	
	belongs_to :tipo
	has_many :filiais


	validates_presence_of :codigo,		:message =>"- Dever ser preenchido"
	validates_presence_of :nome,		:message =>"- Dever ser preenchido"
	validates_presence_of :tipo_id,		:message =>"- Dever ser preenchido"

end

app/controllers/operadoras_controller.rb
class OperadorasController < ApplicationController

	respond_to :json, :js, :html

	def index
		@operadoras = Operadora.order(:nome)   
		respond_with(@operadoras)
	end

  def show
    @operadora = Operadora.find(params[:id])
    respond_with(@operadoras)
  end

  def new
    @operadora = Operadora.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operadora }
    end
  end

  def edit
    @operadora = Operadora.find(params[:id])
  end

  def create
    @operadora = Operadora.new(params[:operadora])

    respond_to do |format|
      if @operadora.save
        format.html { redirect_to @operadora, notice: 'Operadora was successfully created.' }
        format.json { render json: @operadora, status: :created, location: @operadora }
      else
        format.html { render action: "new" }
        format.json { render json: @operadora.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @operadora = Operadora.find(params[:id])

    respond_to do |format|
      if @operadora.update_attributes(params[:operadora])
        format.html { redirect_to @operadora, notice: 'Operadora was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operadora.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @operadora = Operadora.find(params[:id])
    @operadora.destroy

    respond_to do |format|
      format.html { redirect_to operadoras_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/operadoras_helper.rb
module OperadorasHelper
end

app/views/operadoras/_form.html.erb
<%= form_for(@operadora,:html => {:class =>"well form-vertical"}) do |f| %>

  <% if @operadora.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@operadora.errors.count, t(:error)) %>:</h2>

      <ul>
      <% @operadora.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
  </div>

<div class="field">
    <%= f.label :tipo_id %>
    <%= f.collection_select :tipo_id,
        Tipo.all,
        :id,
        :nome,
        {:prompt =>true}
    %>
  </div>


  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit t(:submit),:class =>"btn btn-success" %> | <%= link_to t(:back), operadoras_path, :class =>"btn btn" %>
  </div>
<% end %>

app/views/operadoras/edit.html.erb
<h1>Editing operadora</h1>

<%= render 'form' %>

<%= link_to 'Show', @operadora %> |
<%= link_to 'Back', operadoras_path %>

app/views/operadoras/index.html.erb
<h1><%=t(:list_operators)%></h1>

<table class="table">
  <tr>
    <th>Código</th>
    <th>Nome</th>
    <th>Tipo</th>

    <th></th>
    <th>Ações</th>
    <th></th>
  </tr>

<% @operadoras.each do |operadora| %>
  <tr>
    <td><%= operadora.codigo %></td>
    <td><%= operadora.nome %></td>
    <td><%= operadora.tipo.nome unless operadora.tipo.nil? %></td>

    <td><%= link_to t(:show), operadora,:class=>"btn btn-info" %></td>
    <td><%= link_to t(:edit), edit_operadora_path(operadora),:class=>"btn btn-warning" %></td>
    <td><%= link_to t(:destroy), operadora, confirm: 'Are you sure?', method: :delete,:class=>"btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:new), new_operadora_path,:class=>"btn btn-primary" %>

app/views/operadoras/new.html.erb
<h1><%= t(:new_operator)%></h1>
<%= render 'form' %>

app/views/operadoras/show.html.erb
<h1><%= t(:details)%></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%=@operadora.codigo %>
</p>

<p>
  <b>Nome:</b>
  <%=@operadora.tipo.nome %>
</p>




<%= link_to 'Edit', edit_operadora_path(@operadora) %> |
<%= link_to 'Back', operadoras_path %>